# Multi-language Support for Math Routing Agent

import json
from typing import Dict, Any, Optional, List
from enum import Enum

class SupportedLanguages(Enum):
    ENGLISH = "en"
    SPANISH = "es"
    FRENCH = "fr"
    GERMAN = "de"
    CHINESE = "zh"
    JAPANESE = "ja"
    HINDI = "hi"
    ARABIC = "ar"

class MathTranslationService:
    """Multi-language support for mathematical content"""
    
    def __init__(self):
        self.translations = self._load_translations()
        self.math_term_translations = self._load_math_terms()
    
    def _load_translations(self) -> Dict[str, Dict[str, str]]:
        """Load UI translations for different languages"""
        return {
            "en": {
                "title": "Math Routing Agent",
                "subtitle": "AI-powered math solver with KB, MCP web search, AI generation, and human feedback loop",
                "input_placeholder": "Enter your mathematical question here...",
                "search_button": "Solve Problem",
                "loading": "Solving your problem...",
                "source_kb": "Knowledge Base",
                "source_web": "Web Search (MCP)",
                "source_ai": "AI Generation",
                "source_human": "Human Expert",
                "answer_label": "Answer:",
                "steps_label": "Steps:",
                "summary_label": "Summary:",
                "feedback_title": "Help Us Improve - Provide Feedback",
                "rating_label": "Rate this solution (1-5):",
                "feedback_placeholder": "Please provide your feedback, corrections, or improved solution...",
                "submit_feedback": "Submit Feedback",
                "skip_feedback": "Skip",
                "error_connection": "Failed to connect to backend. Make sure the server is running.",
                "disclaimer": "This answer was generated by AI. Please verify mathematical accuracy."
            },
            "es": {
                "title": "Agente de Enrutamiento Matemático",
                "subtitle": "Solucionador de matemáticas impulsado por IA con KB, búsqueda web MCP, generación IA y bucle de retroalimentación humana",
                "input_placeholder": "Ingresa tu pregunta matemática aquí...",
                "search_button": "Resolver Problema",
                "loading": "Resolviendo tu problema...",
                "source_kb": "Base de Conocimientos",
                "source_web": "Búsqueda Web (MCP)",
                "source_ai": "Generación IA",
                "source_human": "Experto Humano",
                "answer_label": "Respuesta:",
                "steps_label": "Pasos:",
                "summary_label": "Resumen:",
                "feedback_title": "Ayúdanos a Mejorar - Proporciona Comentarios",
                "rating_label": "Califica esta solución (1-5):",
                "feedback_placeholder": "Por favor proporciona tus comentarios, correcciones o solución mejorada...",
                "submit_feedback": "Enviar Comentarios",
                "skip_feedback": "Omitir",
                "error_connection": "Error al conectar con el backend. Asegúrate de que el servidor esté funcionando.",
                "disclaimer": "Esta respuesta fue generada por IA. Por favor verifica la precisión matemática."
            },
            "fr": {
                "title": "Agent de Routage Mathématique",
                "subtitle": "Solveur de mathématiques alimenté par IA avec KB, recherche web MCP, génération IA et boucle de rétroaction humaine",
                "input_placeholder": "Entrez votre question mathématique ici...",
                "search_button": "Résoudre le Problème",
                "loading": "Résolution de votre problème...",
                "source_kb": "Base de Connaissances",
                "source_web": "Recherche Web (MCP)",
                "source_ai": "Génération IA",
                "source_human": "Expert Humain",
                "answer_label": "Réponse:",
                "steps_label": "Étapes:",
                "summary_label": "Résumé:",
                "feedback_title": "Aidez-nous à Améliorer - Fournissez des Commentaires",
                "rating_label": "Évaluez cette solution (1-5):",
                "feedback_placeholder": "Veuillez fournir vos commentaires, corrections ou solution améliorée...",
                "submit_feedback": "Soumettre les Commentaires",
                "skip_feedback": "Ignorer",
                "error_connection": "Échec de connexion au backend. Assurez-vous que le serveur fonctionne.",
                "disclaimer": "Cette réponse a été générée par IA. Veuillez vérifier l'exactitude mathématique."
            },
            "de": {
                "title": "Mathematik-Routing-Agent",
                "subtitle": "KI-gestützter Mathematik-Löser mit KB, MCP-Websuche, KI-Generierung und menschlicher Feedback-Schleife",
                "input_placeholder": "Geben Sie hier Ihre mathematische Frage ein...",
                "search_button": "Problem Lösen",
                "loading": "Löse Ihr Problem...",
                "source_kb": "Wissensbasis",
                "source_web": "Websuche (MCP)",
                "source_ai": "KI-Generierung",
                "source_human": "Menschlicher Experte",
                "answer_label": "Antwort:",
                "steps_label": "Schritte:",
                "summary_label": "Zusammenfassung:",
                "feedback_title": "Helfen Sie uns zu Verbessern - Geben Sie Feedback",
                "rating_label": "Bewerten Sie diese Lösung (1-5):",
                "feedback_placeholder": "Bitte geben Sie Ihr Feedback, Korrekturen oder verbesserte Lösung...",
                "submit_feedback": "Feedback Senden",
                "skip_feedback": "Überspringen",
                "error_connection": "Verbindung zum Backend fehlgeschlagen. Stellen Sie sicher, dass der Server läuft.",
                "disclaimer": "Diese Antwort wurde von KI generiert. Bitte überprüfen Sie die mathematische Genauigkeit."
            },
            "zh": {
                "title": "数学路由代理",
                "subtitle": "AI驱动的数学求解器，具有知识库、MCP网络搜索、AI生成和人工反馈循环",
                "input_placeholder": "在这里输入您的数学问题...",
                "search_button": "解决问题",
                "loading": "正在解决您的问题...",
                "source_kb": "知识库",
                "source_web": "网络搜索 (MCP)",
                "source_ai": "AI生成",
                "source_human": "人类专家",
                "answer_label": "答案：",
                "steps_label": "步骤：",
                "summary_label": "摘要：",
                "feedback_title": "帮助我们改进 - 提供反馈",
                "rating_label": "为此解决方案评分 (1-5)：",
                "feedback_placeholder": "请提供您的反馈、更正或改进的解决方案...",
                "submit_feedback": "提交反馈",
                "skip_feedback": "跳过",
                "error_connection": "连接后端失败。请确保服务器正在运行。",
                "disclaimer": "此答案由AI生成。请验证数学准确性。"
            }
        }
    
    def _load_math_terms(self) -> Dict[str, Dict[str, str]]:
        """Load mathematical term translations"""
        return {
            "en": {
                "derivative": "derivative",
                "integral": "integral",
                "limit": "limit",
                "function": "function",
                "equation": "equation",
                "solve": "solve",
                "calculate": "calculate",
                "find": "find",
                "determine": "determine",
                "evaluate": "evaluate",
                "simplify": "simplify",
                "expand": "expand",
                "factor": "factor",
                "differentiate": "differentiate",
                "integrate": "integrate"
            },
            "es": {
                "derivative": "derivada",
                "integral": "integral",
                "limit": "límite",
                "function": "función",
                "equation": "ecuación",
                "solve": "resolver",
                "calculate": "calcular",
                "find": "encontrar",
                "determine": "determinar",
                "evaluate": "evaluar",
                "simplify": "simplificar",
                "expand": "expandir",
                "factor": "factorizar",
                "differentiate": "diferenciar",
                "integrate": "integrar"
            },
            "fr": {
                "derivative": "dérivée",
                "integral": "intégrale",
                "limit": "limite",
                "function": "fonction",
                "equation": "équation",
                "solve": "résoudre",
                "calculate": "calculer",
                "find": "trouver",
                "determine": "déterminer",
                "evaluate": "évaluer",
                "simplify": "simplifier",
                "expand": "développer",
                "factor": "factoriser",
                "differentiate": "différencier",
                "integrate": "intégrer"
            },
            "de": {
                "derivative": "Ableitung",
                "integral": "Integral",
                "limit": "Grenzwert",
                "function": "Funktion",
                "equation": "Gleichung",
                "solve": "lösen",
                "calculate": "berechnen",
                "find": "finden",
                "determine": "bestimmen",
                "evaluate": "auswerten",
                "simplify": "vereinfachen",
                "expand": "erweitern",
                "factor": "faktorisieren",
                "differentiate": "differenzieren",
                "integrate": "integrieren"
            },
            "zh": {
                "derivative": "导数",
                "integral": "积分",
                "limit": "极限",
                "function": "函数",
                "equation": "方程",
                "solve": "解决",
                "calculate": "计算",
                "find": "找到",
                "determine": "确定",
                "evaluate": "评估",
                "simplify": "简化",
                "expand": "展开",
                "factor": "因式分解",
                "differentiate": "微分",
                "integrate": "积分"
            }
        }
    
    def get_translation(self, key: str, language: str = "en") -> str:
        """Get UI translation for a specific key and language"""
        if language not in self.translations:
            language = "en"  # Fallback to English
        
        return self.translations[language].get(key, self.translations["en"].get(key, key))
    
    def translate_math_term(self, term: str, target_language: str = "en", source_language: str = "en") -> str:
        """Translate mathematical terms between languages"""
        if source_language == target_language:
            return term
        
        # Find the English equivalent first
        english_term = term.lower()
        if source_language != "en":
            source_terms = self.math_term_translations.get(source_language, {})
            for en_term, foreign_term in source_terms.items():
                if foreign_term.lower() == term.lower():
                    english_term = en_term
                    break
        
        # Translate from English to target language
        if target_language != "en" and target_language in self.math_term_translations:
            return self.math_term_translations[target_language].get(english_term, term)
        
        return term
    
    def detect_language(self, text: str) -> str:
        """Simple language detection based on mathematical terms (basic implementation)"""
        text_lower = text.lower()
        
        # Language-specific mathematical terms
        language_indicators = {
            "es": ["derivada", "integral", "función", "ecuación", "resolver", "calcular"],
            "fr": ["dérivée", "intégrale", "fonction", "équation", "résoudre", "calculer"],
            "de": ["ableitung", "integral", "funktion", "gleichung", "lösen", "berechnen"],
            "zh": ["导数", "积分", "函数", "方程", "解决", "计算"]
        }
        
        for lang, indicators in language_indicators.items():
            if any(term in text_lower for term in indicators):
                return lang
        
        return "en"  # Default to English
    
    def localize_response(self, response: Dict[str, Any], language: str = "en") -> Dict[str, Any]:
        """Localize response content based on language"""
        if language == "en":
            return response
        
        localized_response = response.copy()
        
        # Translate standard response fields
        if "source" in localized_response:
            source_map = {
                "Knowledge Base": self.get_translation("source_kb", language),
                "MCP Web Search": self.get_translation("source_web", language),
                "OpenAI GPT": self.get_translation("source_ai", language),
                "Human Expert": self.get_translation("source_human", language)
            }
            original_source = localized_response["source"]
            localized_response["source"] = source_map.get(original_source, original_source)
        
        # Translate disclaimer if present
        if "disclaimer" in localized_response:
            localized_response["disclaimer"] = self.get_translation("disclaimer", language)
        
        # Note: Mathematical content itself would require more sophisticated translation
        # This is a basic framework that can be extended with proper mathematical translation
        
        return localized_response
    
    def get_supported_languages(self) -> List[Dict[str, str]]:
        """Get list of supported languages"""
        return [
            {"code": "en", "name": "English", "native": "English"},
            {"code": "es", "name": "Spanish", "native": "Español"},
            {"code": "fr", "name": "French", "native": "Français"},
            {"code": "de", "name": "German", "native": "Deutsch"},
            {"code": "zh", "name": "Chinese", "native": "中文"}
        ]

# Global translation service
translation_service = MathTranslationService()
