import { useState } from 'react';
import '../styles/ExportPanel.css';

function ExportPanel({ query, result, steps, route }) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [copied, setCopied] = useState('');

  const copyToClipboard = async (text, type) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      setTimeout(() => setCopied(''), 2000);
    } catch (err) {
      alert('Failed to copy to clipboard');
    }
  };

  const exportLatex = () => {
    const latex = `
\\documentclass{article}
\\usepackage{amsmath}
\\begin{document}

\\section*{Problem}
${query}

\\section*{Solution}
${result?.answer || ''}

${steps ? `\\section*{Steps}
${Array.isArray(steps) ? steps.join('\n\n') : steps}` : ''}

\\end{document}
    `.trim();
    copyToClipboard(latex, 'latex');
  };

  const exportMarkdown = () => {
    const markdown = `
# Math Problem Solution

## Problem
${query}

## Answer
${result?.answer || ''}

${steps ? `## Solution Steps
${Array.isArray(steps) ? steps.map((s, i) => `${i + 1}. ${s}`).join('\n') : steps}` : ''}

---
*Solved via: ${route} | Generated by Math Routing Agent*
    `.trim();
    copyToClipboard(markdown, 'markdown');
  };

  const exportPlainText = () => {
    const text = `
PROBLEM:
${query}

ANSWER:
${result?.answer || ''}

${steps ? `STEPS:
${Array.isArray(steps) ? steps.map((s, i) => `Step ${i + 1}: ${s}`).join('\n') : steps}` : ''}

---
Source: ${route}
    `.trim();
    copyToClipboard(text, 'text');
  };

  const saveSolution = () => {
    const solution = {
      query,
      answer: result?.answer,
      steps,
      route,
      timestamp: new Date().toISOString()
    };
    
    const saved = JSON.parse(localStorage.getItem('savedSolutions') || '[]');
    saved.unshift(solution);
    localStorage.setItem('savedSolutions', JSON.stringify(saved.slice(0, 20)));
    
    alert('✅ Solution saved!');
  };

  if (!result) return null;

  return (
    <div className="export-panel">
      <button
        className="export-toggle"
        onClick={() => setIsExpanded(!isExpanded)}
        aria-expanded={isExpanded}
        aria-label={isExpanded ? "Hide export options" : "Show export options"}
      >
        <span className="export-icon">📥</span>
        <strong>Export Solution</strong>
        <span className="toggle-arrow">{isExpanded ? '▼' : '▶'}</span>
      </button>

      {isExpanded && (
        <div className="export-content fade-in">
          <div className="export-buttons">
            <button
              className="export-btn latex-btn"
              onClick={exportLatex}
              title="Copy LaTeX code"
            >
              {copied === 'latex' ? '✅ Copied!' : '📄 Copy LaTeX'}
            </button>

            <button
              className="export-btn markdown-btn"
              onClick={exportMarkdown}
              title="Copy Markdown"
            >
              {copied === 'markdown' ? '✅ Copied!' : '📝 Copy Markdown'}
            </button>

            <button
              className="export-btn text-btn"
              onClick={exportPlainText}
              title="Copy plain text"
            >
              {copied === 'text' ? '✅ Copied!' : '📋 Copy Text'}
            </button>

            <button
              className="export-btn save-btn"
              onClick={saveSolution}
              title="Save solution locally"
            >
              💾 Save Solution
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default ExportPanel;
